name: Setup Node.js Environment

on:
  # Triggered when this workflow is called from another workflow
  workflow_call:
    inputs:
      node-version:
        description: "The version of Node.js to install"
        type: string
        default: "latest" # Default Node.js version if none is provided

  # Allows this workflow to be triggered manually
  workflow_dispatch:
    inputs:
      node-version:
        description: "The version of Node.js to install"
        type: string
        default: "latest" # Default Node.js version if none is provided

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node env with the specified version
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs['node-version'] }} # Use provided or default version
